### ISSUE TITLE
Combine date and time selection into one screen

### ISSUE THREAD

**Issue by welvin21** [rcltech/owl#101]
refer to [raven](https://events.rctech.club)

**Comment by utkarsh867** [comment]
@98sean98 @welvin21 I think this should be a priority.

I have been giving it some thought and I have come across a few problems related to UX on OWL.

At the homepage, the user is being given information that the user does not want. This is probably not good? I think the very first thing that should show up is actually the booking process. And I think the booking process should be a one-page app instead of routing to multiple pages.

This has a lot of advantages. On the UX perspective, this approach allows the user to have the full control, all at once. From the developer point of view, we reduce the complexity caused by passing around and saving all the values.

I guess it will be not that difficult to reorganise the app for UX sake not that we have the components already developed.

**Comment by welvin21** [comment]
> @98sean98 @welvin21 I think this should be a priority.
> 
> I have been giving it some thought and I have come across a few problems related to UX on OWL.
> 
> At the homepage, the user is being given information that the user does not want. This is probably not good? I think the very first thing that should show up is actually the booking process. And I think the booking process should be a one-page app instead of routing to multiple pages.
> 
> This has a lot of advantages. On the UX perspective, this approach allows the user to have the full control, all at once. From the developer point of view, we reduce the complexity caused by passing around and saving all the values.
> 
> I guess it will be not that difficult to reorganise the app for UX sake not that we have the components already developed.

@utkarsh867 @98sean98 i was wondering how the whole booking process would look without routing. probably one big form for all information?? like raven's style? i agree that dev complexity would be reduced tho, still remember passing those information between routes and they disappeared in one refresh click lol

**Comment by utkarsh867** [comment]
stale
