### ISSUE TITLE
Fetch real data to display on ChooseTime component

### ISSUE THREAD

**Issue by welvin21** [rcltech/owl#37]
![image](https://user-images.githubusercontent.com/47080921/66754464-97d99600-eec8-11e9-8b0f-8e6fb6982187.png)

1. This is how the timetable looks like. It is displaying dummy data for now, @98sean98 may i get any endpoint to make a request for the booking data?
2. Also @98sean98, we discussed about merging this frontend branch into master more often. at this point, should I make a pull request?

**Comment by 98sean98** [comment]
1. So far the endpoint remains broken because I haven't setup react to query phoenix directly, we need to integrate with ladybird's login first in order to do that. Also, phoenix doesn't have the Booking / Room type in its database; but I'm sure @utkarsh867 doesn't take long to set that up. For now, we have the option to query the original endpoint which I set up using express, but that's not going to be abandoned going forward. I shall quickly setup another Heroku instance to host that for development purposes.

2. Yes.

**Comment by 98sean98** [comment]
![image](https://user-images.githubusercontent.com/22276614/66763197-02470200-eeda-11e9-82d1-5ffdc045e812.png)
Also, `componentWillMount` is getting deprecated. Please fix. Refer to https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by welvin21** [comment]
alright, let me resolve `componentWillMount` depreciation issue, then I will make a pull request to master.
